// ADMIN LOGOUT
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

//ADMIN DETAILS
export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";
export const ADMIN_DETAILS_RESET = "ADMIN_DETAILS_RESET";

//GET ALL SELLERS
export const GET_ALL_SELLERS_REQUEST = "GET_ALL_SELLERS_REQUEST";
export const GET_ALL_SELLERS_SUCCESS = "GET_ALL_SELLERS_SUCCESS";
export const GET_ALL_SELLERS_FAIL = "GET_ALL_SELLERS_FAIL";
export const GET_ALL_SELLERS_RESET = "GET_ALL_SELLERS_RESET";

// UPDATE SELLER STATUS
export const UPDATE_SELLER_STATUS_REQUEST = "UPDATE_SELLER_STATUS_REQUEST";
export const UPDATE_SELLER_STATUS_SUCCESS = "UPDATE_SELLER_STATUS_SUCCESS";
export const UPDATE_SELLER_STATUS_FAIL = "UPDATE_SELLER_STATUS_FAIL";
export const UPDATE_SELLER_STATUS_RESET = "UPDATE_SELLER_STATUS_RESET";

//GET ALL USER
export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";
export const GET_ALL_USER_RESET = "GET_ALL_USER_RESET";

// UPDATE USER STATUS
export const UPDATE_USER_STATUS_REQUEST = "UPDATE_USER_STATUS_REQUEST";
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS";
export const UPDATE_USER_STATUS_FAIL = "UPDATE_USER_STATUS_FAIL";
export const UPDATE_USER_STATUS_RESET = "UPDATE_USER_STATUS_RESET";

// CREATE MAIN CATEGORY
export const CREATE_MAIN_CATEGORY_REQUEST = "CREATE_MAIN_CATEGORY_REQUEST";
export const CREATE_MAIN_CATEGORY_SUCCESS = "CREATE_MAIN_CATEGORY_SUCCESS";
export const CREATE_MAIN_CATEGORY_FAIL = "CREATE_MAIN_CATEGORY_FAIL";
export const CREATE_MAIN_CATEGORY_RESET = "CREATE_MAIN_CATEGORY_RESET";

// DELETE MAIN CATEGORY
export const DELETE_MAIN_CATEGORY_REQUEST = "DELETE_MAIN_CATEGORY_REQUEST";
export const DELETE_MAIN_CATEGORY_SUCCESS = "DELETE_MAIN_CATEGORY_SUCCESS";
export const DELETE_MAIN_CATEGORY_FAIL = "DELETE_MAIN_CATEGORY_FAIL";

// CREATE SUB CATEGORY
export const CREATE_SUB_CATEGORY_REQUEST = "CREATE_SUB_CATEGORY_REQUEST";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_FAIL = "CREATE_SUB_CATEGORY_FAIL";
export const CREATE_SUB_CATEGORY_RESET = "CREATE_SUB_CATEGORY_RESET";

// DELETE SUB CATEGORY
export const DELETE_SUB_CATEGORY_REQUEST = "DELETE_SUB_CATEGORY_REQUEST";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAIL = "DELETE_SUB_CATEGORY_FAIL";

// CREATE MAIN CATEGORY
export const CREATE_TYPE_OF_PRODUCT_REQUEST = "CREATE_TYPE_OF_PRODUCT_REQUEST";
export const CREATE_TYPE_OF_PRODUCT_SUCCESS = "CREATE_TYPE_OF_PRODUCT_SUCCESS";
export const CREATE_TYPE_OF_PRODUCT_FAIL = "CREATE_TYPE_OF_PRODUCT_FAIL";
export const CREATE_TYPE_OF_PRODUCT_RESET = "CREATE_TYPE_OF_PRODUCT_RESET";

// DELETE TYPE OF PRODUCT
export const DELETE_TYPE_OF_PRODUCT_REQUEST = "DELETE_TYPE_OF_PRODUCT_REQUEST";
export const DELETE_TYPE_OF_PRODUCT_SUCCESS = "DELETE_TYPE_OF_PRODUCT_SUCCESS";
export const DELETE_TYPE_OF_PRODUCT_FAIL = "DELETE_TYPE_OF_PRODUCT_FAIL";

// GET ALL SUB CATEGORY
export const GET_ALL_SUB_CATEGORY_REQUEST = "GET_ALL_SUB_CATEGORY_REQUEST";
export const GET_ALL_SUB_CATEGORY_SUCCESS = "GET_ALL_SUB_CATEGORY_SUCCESS";
export const GET_ALL_SUB_CATEGORY_FAIL = "GET_ALL_SUB_CATEGORY_FAIL";
