// ADMIN LOGOUT
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

//ADMIN DETAILS
export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";
export const ADMIN_DETAILS_RESET = "ADMIN_DETAILS_RESET";

//GET ALL SELLERS
export const GET_ALL_SELLERS_REQUEST = "GET_ALL_SELLERS_REQUEST";
export const GET_ALL_SELLERS_SUCCESS = "GET_ALL_SELLERS_SUCCESS";
export const GET_ALL_SELLERS_FAIL = "GET_ALL_SELLERS_FAIL";
export const GET_ALL_SELLERS_RESET = "GET_ALL_SELLERS_RESET";
