// IMAGE UPLOAD
export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL";

// CREATE SHOP

export const CREATE_SHOP_REQUEST = "CREATE_SHOP_REQUEST";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";
export const CREATE_SHOP_FAIL = "CREATE_SHOP_FAIL";

// GET TYPE OF PRODUCT
export const GET_TYPEOFPROD_REQUEST = "GET_TYPEOFPROD_REQUEST";
export const GET_TYPEOFPROD_SUCCESS = "GET_TYPEOFPROD_SUCCESS";
export const GET_TYPEOFPROD_FAIL = "GET_TYPEOFPROD_FAIL";

// CREATE PRODUCT

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

// SELLER DETAILS
export const SELLER_DETAILS_REQUEST = "SELLER_DETAILS_REQUEST";
export const SELLER_DETAILS_SUCCESS = "SELLER_DETAILS_SUCCESS";
export const SELLER_DETAILS_FAIL = "SELLER_DETAILS_FAIL";
export const SELLER_DETAILS_RESET = "SELLER_DETAILS_RESET";

// SELLER PROFILE UPDATE
export const SELLER_UPDATE_PROFILE_REQUEST = "SELLER_UPDATE_PROFILE_REQUEST";
export const SELLER_UPDATE_PROFILE_SUCCESS = "SELLER_UPDATE_PROFILE_SUCCESS";
export const SELLER_UPDATE_PROFILE_FAIL = "SELLER_UPDATE_PROFILE_FAIL";
export const SELLER_UPDATE_PROFILE_RESET = "SELLER_UPDATE_PROFILE_RESET";

// GET PRODUCT BY SELLER
export const GET_PRODUCTBYSELLER_REQUEST = "GET_PRODUCTBYSELLER_REQUEST";
export const GET_PRODUCTBYSELLER_SUCCESS = "GET_PRODUCTBYSELLER_SUCCESS";
export const GET_PRODUCTBYSELLER_FAIL = "GET_PRODUCTBYSELLER_FAIL";
