// LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// LOGOUT
export const USER_LOGOUT = "USER_LOGOUT";

// Registration
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// USER DETAILS
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

// USER PROFILE UPDATE
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

// GET RANDOM PRODUCTS
export const GET_RANDOM_4_PRODUCTS_REQUEST = "GET_RANDOM_PRODUCTS_REQUEST";
export const GET_RANDOM_4_PRODUCTS_SUCCESS = "GET_RANDOM_PRODUCTS_SUCCESS";
export const GET_RANDOM_4_PRODUCTS_FAIL = "GET_RANDOM_PRODUCTS_FAIL";

// GET PRODUCT DETAILS
export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

// GET SELLER BY ID
export const GET_SELLER_BY_ID_REQUEST = "GET_SELLER_BY_ID_REQUEST";
export const GET_SELLER_BY_ID_SUCCESS = "GET_SELLER_BY_ID_SUCCESS";
export const GET_SELLER_BY_ID_FAIL = "GET_SELLER_BY_ID_FAIL";

// GET USER BY ID
export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";
export const GET_USER_BY_ID_RESET = "GET_USER_BY_ID_RESET";

// GET RANDOM SUB CATEGORY
export const GET_RANDOM_SUB_CATEGORY_REQUEST =
  "GET_RANDOM_SUB_CATEGORY_REQUEST";
export const GET_RANDOM_SUB_CATEGORY_SUCCESS =
  "GET_RANDOM_SUB_CATEGORY_SUCCESS";
export const GET_RANDOM_SUB_CATEGORY_FAIL = "GET_RANDOM_SUB_CATEGORY_FAIL";

// GET RANDOM PRODUCT BY CATEGORY
export const GET_RANDOM_PRODUCT_BY_CATEGORY_REQUEST =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_RANDOM_PRODUCT_BY_CATEGORY_SUCCESS =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_RANDOM_PRODUCT_BY_CATEGORY_FAIL =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_FAIL";
export const GET_RANDOM_PRODUCT_BY_CATEGORY_RESET =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_RESET";

// // GET ALL PRODUCTS BY CATEGORY
// export const GET_ALL_PRODUCT_BY_CATEGORY_REQUEST =
//   "GET_ALL_PRODUCT_BY_CATEGORY_REQUEST";
// export const GET_ALL_PRODUCT_BY_CATEGORY_SUCCESS =
//   "GET_ALL_PRODUCT_BY_CATEGORY_SUCCESS";
// export const GET_ALL_PRODUCT_BY_CATEGORY_FAIL =
//   "GET_ALL_PRODUCT_BY_CATEGORY_FAIL";

// GET SUB CATEGORY BY MAIN CATEGORY NAME
export const GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_REQUEST =
  "GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_REQUEST";
export const GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_SUCCESS =
  "GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_SUCCESS";
export const GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_FAIL =
  "GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_FAIL";

// GET ALL PRODUCTS BY SUB CATEGORY NAME
export const GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_REQUEST =
  "GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_REQUEST";
export const GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_SUCCESS =
  "GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_SUCCESS";
export const GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_FAIL =
  "GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_FAIL";

// GET SUB CATEGORY BY SUB CATEGORY NAME
export const GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_REQUEST =
  "GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_REQUEST";
export const GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_SUCCESS =
  "GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_SUCCESS";
export const GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_FAIL =
  "GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_FAIL";

// ADD TO CART
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

// GET CART DATA BY USER
export const GET_CART_DATA_BY_USER_REQUEST = "GET_CART_DATA_BY_USER_REQUEST";
export const GET_CART_DATA_BY_USER_SUCCESS = "GET_CART_DATA_BY_USER_SUCCESS";
export const GET_CART_DATA_BY_USER_FAIL = "GET_CART_DATA_BY_USER_FAIL";
export const GET_CART_DATA_BY_USER_RESET = "GET_CART_DATA_BY_USER_RESET";

// GET PRODUCT BY ID
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";
export const GET_PRODUCT_BY_ID_RESET = "GET_PRODUCT_BY_ID_RESET";

// REMOVE PRODUCT FROM CART
export const REMOVE_PRODUCT_FROM_CART_REQUEST =
  "REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
  "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAIL = "REMOVE_PRODUCT_FROM_CART_FAIL";

//UPDATE CART BY PRODUCT
// export const UPDATE_CART_BY_PRODUCT_REQUEST = "UPDATE_CART_BY_PRODUCT_REQUEST";
// export const UPDATE_CART_BY_PRODUCT_SUCCESS = "UPDATE_CART_BY_PRODUCT_SUCCESS";
// export const UPDATE_CART_BY_PRODUCT_FAIL = "UPDATE_CART_BY_PRODUCT_FAIL";

// GET SHIPPING ADDRESS BY USER
export const GET_SHIPPING_ADDRESS_BY_USER_REQUEST =
  "GET_SHIPPING_ADDRESS_BY_USER_REQUEST";
export const GET_SHIPPING_ADDRESS_BY_USER_SUCCESS =
  "GET_SHIPPING_ADDRESS_BY_USER_SUCCESS";
export const GET_SHIPPING_ADDRESS_BY_USER_FAIL =
  "GET_SHIPPING_ADDRESS_BY_USER_FAIL";
export const GET_SHIPPING_ADDRESS_BY_USER_RESET =
  "GET_SHIPPING_ADDRESS_BY_USER_RESET";

// ADD SHIPPING ADDRESS
export const ADD_SHIPPING_ADDRESS_REQUEST = "ADD_SHIPPING_ADDRESS_REQUEST";
export const ADD_SHIPPING_ADDRESS_SUCCESS = "ADD_SHIPPING_ADDRESS_SUCCESS";
export const ADD_SHIPPING_ADDRESS_FAIL = "ADD_SHIPPING_ADDRESS_FAIL";

// DELETE SHIPPING ADDRESS
export const DELETE_SHIPPING_ADDRESS_REQUEST =
  "DELETE_SHIPPING_ADDRESS_REQUEST";
export const DELETE_SHIPPING_ADDRESS_SUCCESS =
  "DELETE_SHIPPING_ADDRESS_SUCCESS";
export const DELETE_SHIPPING_ADDRESS_FAIL = "DELETE_SHIPPING_ADDRESS_FAIL";

// GET SHIPPING ADDRESS BY ID
export const GET_SHIPPING_ADDRESS_BY_ID_REQUEST =
  "GET_SHIPPING_ADDRESS_BY_ID_REQUEST";
export const GET_SHIPPING_ADDRESS_BY_ID_SUCCESS =
  "GET_SHIPPING_ADDRESS_BY_ID_SUCCESS";
export const GET_SHIPPING_ADDRESS_BY_ID_FAIL =
  "GET_SHIPPING_ADDRESS_BY_ID_FAIL";

// ADD ORDER MASTER
export const ADD_ORDER_MASTER_REQUEST = "ADD_ORDER_MASTER_REQUEST";
export const ADD_ORDER_MASTER_SUCCESS = "ADD_ORDER_MASTER_SUCCESS";
export const ADD_ORDER_MASTER_FAIL = "ADD_ORDER_MASTER_FAIL";
export const ADD_ORDER_MASTER_RESET = "ADD_ORDER_MASTER_RESET";

// REMOVE CART DATA BY USER
export const REMOVE_CART_DATA_BY_USER_REQUEST =
  "REMOVE_CART_DATA_BY_USER_REQUEST";
export const REMOVE_CART_DATA_BY_USER_SUCCESS =
  "REMOVE_CART_DATA_BY_USER_SUCCESS";
export const REMOVE_CART_DATA_BY_USER_FAIL = "REMOVE_CART_DATA_BY_USER_FAIL";

// ADD ORDER DETAILS
export const ADD_ORDER_DETAILS_REQUEST = "ADD_ORDER_DETAILS_REQUEST";
export const ADD_ORDER_DETAILS_SUCCESS = "ADD_ORDER_DETAILS_SUCCESS";
export const ADD_ORDER_DETAILS_FAIL = "ADD_ORDER_DETAILS_FAIL";
export const ADD_ORDER_DETAILS_RESET = "ADD_ORDER_DETAILS_RESET";

// GET ORDER MASTER
export const GET_ORDER_MASTER_REQUEST = "GET_ORDER_MASTER_REQUEST";
export const GET_ORDER_MASTER_SUCCESS = "GET_ORDER_MASTER_SUCCESS";
export const GET_ORDER_MASTER_FAIL = "GET_ORDER_MASTER_FAIL";
export const GET_ORDER_MASTER_RESET = "GET_ORDER_MASTER_RESET";

// GET ORDER DETAILS
export const GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL";
export const GET_ORDER_DETAILS_RESET = "GET_ORDER_DETAILS_RESET";

// ADD PRODUCT TO MY COLLECTION
export const ADD_PRODUCT_TO_MY_COLLECTION_REQUEST =
  "ADD_PRODUCT_TO_MY_COLLECTION_REQUEST";
export const ADD_PRODUCT_TO_MY_COLLECTION_SUCCESS =
  "ADD_PRODUCT_TO_MY_COLLECTION_SUCCESS";
export const ADD_PRODUCT_TO_MY_COLLECTION_FAIL =
  "ADD_PRODUCT_TO_MY_COLLECTION_FAIL";

//GET PRODUCTS FROM MY COLLECTION
export const GET_PRODUCTS_FROM_MYCOLLECTION_REQUEST =
  "GET_PRODUCTS_FROM_MYCOLLECTION_REQUEST";
export const GET_PRODUCTS_FROM_MYCOLLECTION_SUCCESS =
  "GET_PRODUCTS_FROM_MYCOLLECTION_SUCCESS";
export const GET_PRODUCTS_FROM_MYCOLLECTION_FAIL =
  "GET_PRODUCTS_FROM_MYCOLLECTION_FAIL";
export const GET_PRODUCTS_FROM_MYCOLLECTION_RESET =
  "GET_PRODUCTS_FROM_MYCOLLECTION_RESET";

// REMOVE PRODUCT FROM MY COLLECTION
export const REMOVE_PRODUCT_FROM_MYCOLLECTION_REQUEST =
  "REMOVE_PRODUCT_FROM_MYCOLLECTION_REQUEST";
export const REMOVE_PRODUCT_FROM_MYCOLLECTION_SUCCESS =
  "REMOVE_PRODUCT_FROM_MYCOLLECTION_SUCCESS";
export const REMOVE_PRODUCT_FROM_MYCOLLECTION_FAIL =
  "REMOVE_PRODUCT_FROM_MYCOLLECTION_FAIL";

// ADD REVIEW FOR PRODUCT
export const ADD_REVIEW_FOR_PRODUCT_REQUEST = "ADD_REVIEW_FOR_PRODUCT_REQUEST";
export const ADD_REVIEW_FOR_PRODUCT_SUCCESS = "ADD_REVIEW_FOR_PRODUCT_SUCCESS";
export const ADD_REVIEW_FOR_PRODUCT_FAIL = "ADD_REVIEW_FOR_PRODUCT_FAIL";
export const ADD_REVIEW_FOR_PRODUCT_RESET = "ADD_REVIEW_FOR_PRODUCT_RESET";

// CHANGE PASSWORD
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

// DEACTIVATE USER ACCOUNT
export const DEACTIVATE_USER_ACCOUNT_REQUEST =
  "DEACTIVATE_USER_ACCOUNT_REQUEST";
export const DEACTIVATE_USER_ACCOUNT_SUCCESS =
  "DEACTIVATE_USER_ACCOUNT_SUCCESS";
export const DEACTIVATE_USER_ACCOUNT_FAIL = "DEACTIVATE_USER_ACCOUNT_FAIL";

// GET ALL RANDOM PRODUCT
export const GET_ALL_RANDOM_PRODUCT_REQUEST = "GET_ALL_RANDOM_PRODUCT_REQUEST";
export const GET_ALL_RANDOM_PRODUCT_SUCCESS = "GET_ALL_RANDOM_PRODUCT_SUCCESS";
export const GET_ALL_RANDOM_PRODUCT_FAIL = "GET_ALL_RANDOM_PRODUCT_FAIL";

//LIKE PRODUCT
export const LIKE_PRODUCT_REQUEST = "LIKE_PRODUCT_REQUEST";
export const LIKE_PRODUCT_SUCCESS = "LIKE_PRODUCT_SUCCESS";
export const LIKE_PRODUCT_FAIL = "LIKE_PRODUCT_FAIL";

// GET FEATURED PRODUCTS
export const GET_FEATURED_PRODUCTS_REQUEST = "GET_FEATURED_PRODUCTS_REQUEST";
export const GET_FEATURED_PRODUCTS_SUCCESS = "GET_FEATURED_PRODUCTS_SUCCESS";
export const GET_FEATURED_PRODUCTS_FAIL = "GET_FEATURED_PRODUCTS_FAIL";
