// LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// LOGOUT
export const USER_LOGOUT = "USER_LOGOUT";

// Registration
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// USER DETAILS
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

// USER PROFILE UPDATE
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

// GET RANDOM PRODUCTS
export const GET_RANDOM_4_PRODUCTS_REQUEST = "GET_RANDOM_PRODUCTS_REQUEST";
export const GET_RANDOM_4_PRODUCTS_SUCCESS = "GET_RANDOM_PRODUCTS_SUCCESS";
export const GET_RANDOM_4_PRODUCTS_FAIL = "GET_RANDOM_PRODUCTS_FAIL";

// GET PRODUCT DETAILS
export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

// GET SELLER BY ID
export const GET_SELLER_BY_ID_REQUEST = "GET_SELLER_BY_ID_REQUEST";
export const GET_SELLER_BY_ID_SUCCESS = "GET_SELLER_BY_ID_SUCCESS";
export const GET_SELLER_BY_ID_FAIL = "GET_SELLER_BY_ID_FAIL";

// GET USER BY ID
export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";
export const GET_USER_BY_ID_RESET = "GET_USER_BY_ID_RESET";

// GET RANDOM SUB CATEGORY
export const GET_RANDOM_SUB_CATEGORY_REQUEST =
  "GET_RANDOM_SUB_CATEGORY_REQUEST";
export const GET_RANDOM_SUB_CATEGORY_SUCCESS =
  "GET_RANDOM_SUB_CATEGORY_SUCCESS";
export const GET_RANDOM_SUB_CATEGORY_FAIL = "GET_RANDOM_SUB_CATEGORY_FAIL";

// GET RANDOM PRODUCT BY CATEGORY
export const GET_RANDOM_PRODUCT_BY_CATEGORY_REQUEST =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_RANDOM_PRODUCT_BY_CATEGORY_SUCCESS =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_RANDOM_PRODUCT_BY_CATEGORY_FAIL =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_FAIL";
export const GET_RANDOM_PRODUCT_BY_CATEGORY_RESET =
  "GET_RANDOM_PRODUCT_BY_CATEGORY_RESET";

// // GET ALL PRODUCTS BY CATEGORY
// export const GET_ALL_PRODUCT_BY_CATEGORY_REQUEST =
//   "GET_ALL_PRODUCT_BY_CATEGORY_REQUEST";
// export const GET_ALL_PRODUCT_BY_CATEGORY_SUCCESS =
//   "GET_ALL_PRODUCT_BY_CATEGORY_SUCCESS";
// export const GET_ALL_PRODUCT_BY_CATEGORY_FAIL =
//   "GET_ALL_PRODUCT_BY_CATEGORY_FAIL";

// GET SUB CATEGORY BY MAIN CATEGORY NAME
export const GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_REQUEST =
  "GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_REQUEST";
export const GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_SUCCESS =
  "GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_SUCCESS";
export const GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_FAIL =
  "GET_SUBCATEGORY_BY_MAINCATEGORY_NAME_FAIL";

// GET ALL PRODUCTS BY SUB CATEGORY NAME
export const GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_REQUEST =
  "GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_REQUEST";
export const GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_SUCCESS =
  "GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_SUCCESS";
export const GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_FAIL =
  "GET_ALL_PRODUCT_BY_SUB_CATEGORY_NAME_FAIL";

// GET SUB CATEGORY BY SUB CATEGORY NAME
export const GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_REQUEST =
  "GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_REQUEST";
export const GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_SUCCESS =
  "GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_SUCCESS";
export const GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_FAIL =
  "GET_SUBCATEGORY_BY_SUBCATEGORY_NAME_FAIL";

// ADD TO CART
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

// GET CART DATA BY USER
export const GET_CART_DATA_BY_USER_REQUEST = "GET_CART_DATA_BY_USER_REQUEST";
export const GET_CART_DATA_BY_USER_SUCCESS = "GET_CART_DATA_BY_USER_SUCCESS";
export const GET_CART_DATA_BY_USER_FAIL = "GET_CART_DATA_BY_USER_FAIL";
export const GET_CART_DATA_BY_USER_RESET = "GET_CART_DATA_BY_USER_RESET";

// GET PRODUCT BY ID
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";
export const GET_PRODUCT_BY_ID_RESET = "GET_PRODUCT_BY_ID_RESET";

// REMOVE PRODUCT FROM CART
export const REMOVE_PRODUCT_FROM_CART_REQUEST =
  "REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
  "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAIL = "REMOVE_PRODUCT_FROM_CART_FAIL";
